### ISSUE TITLE
PHP Fatal error in 1.4.2

### ISSUE THREAD

**Issue by pjv** [discourse/wp-discourse#285] opened 2017-07-22 12:52 UTC
Here's a weird one. I was creating a new MailPoet email and when doing anything in the newsletter editor where mailpoet puts up a modal and fills it with an ajax get, it was failing with a 500 error.

When I finally ruled out everything obvious and looked carefully at the PHP error log, it turned out that it was wp-discourse that was giving the fatal error.

`[22-Jul-2017 12:07:10 UTC] PHP Fatal error:  Uncaught Error: Call to a member function in_admin() on null in /var/www/breadtopia.com/htdocs/wp-content/plugins/wp-discourse/admin/admin.php:60`

The problem appears to be something to do with initializing on non-multisite. I don't know what the best fix would be, but I got past it on my site by editing `enqueue_network_styles()` in `admin.php` as follows:

```
/**
 * Enqueue styles for network page.
 */
function enqueue_network_styles() {
	global $current_screen;
	if ( ! isset( $current_screen ) ) {

		return;
	}
	if ( ! $current_screen->in_admin( 'network' ) ) {

		return;
	}

	wp_register_style( 'wp_discourse_network_admin', WPDISCOURSE_URL . '/admin/css/network-admin-styles.css' );
	wp_enqueue_style( 'wp_discourse_network_admin' );
}
```

**Comment by scossar** [comment] 2017-07-22 14:56
Thanks! I'll fix that right away.

**Comment by scossar** [comment] 2017-07-22 20:48
It is odd. I can't reproduce it in my development environment with the latest version of MailPoet. Using the `admin_print_scripts` hook to add styles to the network page seems wrong though. I'll try to find another way to do it. If I can't find one, I'll use something like the solution you found. There will be a fix for this in the next update. I'll try to get it out later today, or early tomorrow.

**Comment by pjv** [comment] 2017-07-23 12:07
let me know if you want me to field test a beta before you push to WP.org.

**Comment by scossar** [comment] 2017-10-12 23:49
This should be working correctly now.

**Closed by scossar** 2017-10-12 23:49 UTC
