### ISSUE TITLE
Emoji image broken

### ISSUE THREAD

**Issue by paxmanchris** [discourse/wp-discourse#142] opened 2015-05-02 11:07 UTC
Emoji url seems to use a path, an not the url of the discourse site:
![screen shot 2015-05-02 at 7 05 04 pm](https://cloud.githubusercontent.com/assets/8140248/7440830/3c144af8-f0fe-11e4-96a4-83f36e5c1ebc.png)

It is pointing to this:
**/images/emoji/emoji_one/smile.png?v=0**

but should have the url of the discourse site. I am working with 4f6e7997733692799196e5ed5e3a6e7702de14dd.

**Comment by retlehs** [comment] 2016-05-18 18:31
still experiencing this?

**Comment by Swissendo** [comment] 2016-07-20 14:27
I have exactly the same problem. It never affected all posts/comments for me though, sometimes Emojis from another comment in the same topic were fine. But it seems that upgrading to 0.9.1 made it a lot worse, a lot of Emojis that had the correct URL before are now broken as well.

**Comment by scossar** [comment] 2016-07-20 15:31
Thanks. I'll fix that in the next couple of hours and update the plugin.

**Comment by scossar** [comment] 2016-07-20 18:02
I've added a partial fix for this. The problem is that Discourse has been giving the emojis relative paths. This has been fixed in the most recent version of Discourse.

As it is now, if this fix works as expected, emojis will have the correct path unless they are in a comment that has an image occurring before the emoji.

**Comment by Swissendo** [comment] 2016-07-21 06:46
Awesome, this fixed all broken Emojis for me. Thank you so much for this quick fix!

**Closed** 2017-04-14 00:45 UTC
