### ISSUE TITLE
Published category being ignored

### ISSUE THREAD

**Issue by pixeldynamo** [discourse/wp-discourse#107] opened 2015-01-06 21:03 UTC
Since the change which allows posts to be created in different Discourse categories if they match Wordpress categories, the specified 'Published Category' in the plugin settings is now being ignored.

All posts are being created under 'Off-Topic' rather than 'Article Discussion'.

**Comment by coding-horror** [comment] 2015-01-06 21:46
Oh that's not good cc: @techAPJ 

If it fails to find a match on the WP side it should always use the category selected in 'Published Category'

**Comment by pixeldynamo** [comment] 2015-01-06 21:48
We implemented 0.6.1 over the weekend, am testing again with 0.6.2.

**Comment by techAPJ** [comment] 2015-01-07 03:42
This issue is fixed via #99. (also see #92)

Now, only if “Published category” setting is null, the plugin will check for WP category and publish in that category.

**Comment by pixeldynamo** [comment] 2015-01-07 07:24
We're still seeing this today with 0.6.2

**Comment by techAPJ** [comment] 2015-01-07 07:31
The PR was merged after version `0.6.2` was released.

I just bumped the version to `0.6.3`, could you please test the same against the latest version?

**Comment by pixeldynamo** [comment] 2015-01-07 08:21
Still happening with 0.6.3

**Comment by techAPJ** [comment] 2015-01-07 08:31
I will not be able to look into this issue until Saturday :disappointed: 

cc @henrynet, @retlehs: any help here would be appreciated.

**Comment by henrynet** [comment] 2015-01-07 09:14
I have tested 0.6.3 and I cannot see any wrong within it.

@pixeldynamo What is your 'Published Category' in the plugin settings?

**Comment by pixeldynamo** [comment] 2015-01-07 09:21
Our Published Category matches the name of the category on Discourse.

To be clear, this was working fine before Christmas, it's only since the inclusion of the new feature to match categories that posts have been placed elsewhere.

I've been doing some testing, prior to the issue arising our published category and category were both 'Articles'. We had a plan to rename the category 'Article Discussion' which we did when we noticed the problem with 0.6.1 (and reflected the change in the settings on the Discourse plugin). Since testing 0.6.2 and 0.6.3 both the category on our Discourse, and the entry in the plugin, have been reverted to 'Articles'.

**Comment by henrynet** [comment] 2015-01-07 09:39
I have tested in my environment both category name 'Articles' and 'Article Discussion' work OK.

Can you check your 'Published Category' setting is 'Articles' or 'Articles ' (an extra space makes the category name different)?

**Comment by pixeldynamo** [comment] 2015-01-07 10:08
![screen shot 2015-01-07 at 10 07 08](https://cloud.githubusercontent.com/assets/10160987/5643866/2b00213c-9655-11e4-96d8-889f8f036381.png)

**Comment by retlehs** [comment] 2015-04-12 17:24
unable to reproduce

**Closed by retlehs** 2015-04-12 17:24 UTC
